exception_codes = {
    "E1000": "General error",
    "E1001": "Validation error",
    "E1002": "Incorrect identifier or password",
    "E1003": "Invalid phone number",
    "E1004": "Invalid email",
    "E1005": "Invalid password",
    "E1006": "Invalid OTP",
    "E1007": "Invalid token",
    "E1008": "Invalid refresh token",
    "E1009": "Invalid user",
    "E1010": "Invalid business",
    "E1011": "Invalid agency",
    "E1012": "Invalid identifier. Must be an email or phone number in E.164 format",
    "E1013": "User not active",
    "E1014": "OTP timeout.",
    "E1015": "OTP login not allowed",
    "E1016": "Token expired",
    "E1017": "Refresh token expired or invalid",
    "E1018": "Invalid Access Token",
    "E1019": "Invalid Refresh Token",
    "E1020": "Invalid Group id",
    "E1021": "User already has a password. Use Change Password instead",
    "E1022": "Invalid Permission.",
    "E1023": "Not found",
    "E1024": "No IPG found for this currency",
    "E1025": "Invalid Transaction, please contact support",
    "E1026": "Transaction is in verifying state",
    "E1027": "Transaction is not in pending state, please contact support",
    "E1028": "User already exists",
    "E1029": "User already assigned to a business",
    "E1030": "Invalid permission. Current user type does not have permission to access this resource",
    "E1031": "Business ID is required.",
    "E1032": "Business is deleted.",
}
